### ISSUE TITLE
Add dialect as a module dependency rather than a string (Running Join Monster in React Native)

### ISSUE THREAD

**Issue by tslater** [join-monster/join-monster#172]
## Context:
I'm currently running Join Monster on React Native! This means that I can use Relay or Apollo Client, offline, on an embedded sqlite database, sans server. Here's a shot of it working:

<a href="url"><img src="https://user-images.githubusercontent.com/449326/28643278-92801b96-7212-11e7-9e18-a84449dc6bd3.png" height="500" ></a>

In order to get this to work, I _only_ had to do things!
1. Shim Nodejs modules
2. Hard code the dialect in the join-monster source code

The first is something I think I can just deal with, and wasn't so bad. The latter is problematic because I don't want to maintain my own fork of this awesome package.

## Problem

The reason why I had to hardcode the dialect is because React Native can't dynamically require modules: https://github.com/facebook/react-native/issues/6391.

I ended up hard coding sqlite as the dialact on this line: https://github.com/stems/join-monster/blob/master/src/stringifiers/dispatcher.js#L13

See my atrocity below:

```
import sqlite from './dialects/sqlite3'

export default async function stringifySqlAST(topNode, context, options) {
  validateSqlAST(topNode)
  const dialect = sqlite
  // recursively figure out all the selections, joins, and where conditions that we need
  let { selections, tables, wheres, orders } = await _stringifySqlAST(
    null, topNode, [],
    context, [], [],
    [], [], options.batchScope,
    dialect
  )
```
## Proposal
Instead of having a string option for the dialect, we make it an actual imported dialect instance:

```
import joinMonster from 'join-monster'
import {pg} from 'join-monster/dialects'

const options = { dialectModule: pg}
 joinMonster(resolveInfo, context, sql => dbCall(sql, knex, context), options)
```

This would also let people write custom dialects or tweak them, without having to modify Join Monster itself. If the maintainers like the proposal, I'd be happy to attempt a PR.

**Comment by acarl005** [comment]
Great idea! I would like it to be backward compatible. So either a string or module can be passed. Happy to accept a PR.

**Comment by tslater** [comment]
I thought that you'd probably prefer that, so I chose `dialectModule` instead of `dialect` for the option name in my example. I'm not in love with that option name, but it's the best I can think of right now. @acarl005, let me know if you have a preference there, otherwise I'll start with `dialectModule`.

**Comment by acarl005** [comment]
That name is clear enough. Sound good to me.

**Comment by tslater** [comment]
I started with the contribution guide: https://github.com/stems/join-monster/blob/master/CONTRIBUTING.md and am running `npm run db-build`. I got errors about not having a MySQL connection string. I provided that but then the `test1` database was missing. I created the database, and now I'm getting `ERROR 1067 (42000) at line 2: Invalid default value for 'created_at'`. I haven't edited any code yet. Am I starting off on the wrong foot here?

**Comment by acarl005** [comment]
Thats odd. What version of MySQL are you using?

**Comment by tslater** [comment]
5.7.19-log

**Comment by tslater** [comment]
This works:

```
mysql> CREATE TABLE accounts (
    ->   id INT AUTO_INCREMENT PRIMARY KEY,
    ->   email_address VARCHAR(150),
    ->   first_name VARCHAR(255),
    ->   last_name VARCHAR(255),
    ->   num_legs INT DEFAULT 2,
    ->   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    -> );
```

I think it has to do with the precision of DATETIME(3) not working with the default timestamp?

**Comment by tslater** [comment]
I removed all those and ran it, and a lot of my tests are passing, but now I'm getting this:
```
connection to { client: 'mysql', connection: 'mysql://root:@localhost/test2' }

  1 failed

  filtered pagination at the root
  /Users/admin/playground/join-monster/test/pagination/offset-paging.js:402

   401:   const { data, errors } = await run(query)
   402:   t.is(errors, undefined)                  
   403:   t.deepEqual(data, {                      

  Difference:

  - [
  -   GraphQLError { … },
  - ]
  + undefined

  Test.<anonymous> (test/pagination/offset-paging.js:402:5)
  step (test/pagination/offset-paging.js:19:191)
```

**Comment by tslater** [comment]
Here is the error:
```
[ { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '() AS `$total`
    FROM (SELECT * FROM `accounts`) `users`
    WHERE TRUE
    ORDER BY' at line 7
      at Query.Sequence._packetToError (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
      at Query.ErrorPacket (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
      at Protocol._parsePacket (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/Users/admin/playground/join-monster/node_modules/mysql/lib/Connection.js:103:28)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:252:12)
      at readableAddChunk (_stream_readable.js:239:11)
      at Socket.Readable.push (_stream_readable.js:197:10)
      at TCP.onread (net.js:589:20)
      at Protocol._enqueue (/Users/admin/playground/join-monster/node_modules/mysql/lib/protocol/Protocol.js:141:48)
      at Connection.query (/Users/admin/playground/join-monster/node_modules/mysql/lib/Connection.js:208:25)
      at /Users/admin/playground/join-monster/node_modules/knex/lib/dialects/mysql/index.js:152:18
  From previous event:
      at Client_MySQL._query (/Users/admin/playground/join-monster/node_modules/knex/lib/dialects/mysql/index.js:146:12)
      at Client_MySQL.query (/Users/admin/playground/join-monster/node_modules/knex/lib/client.js:197:17)
      at Runner.<anonymous> (/Users/admin/playground/join-monster/node_modules/knex/lib/runner.js:146:36)
  From previous event:
      at /Users/admin/playground/join-monster/node_modules/knex/lib/runner.js:65:21
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
  From previous event:
      at Runner.run (/Users/admin/playground/join-monster/node_modules/knex/lib/runner.js:51:31)
      at Raw.Target.then (/Users/admin/playground/join-monster/node_modules/knex/lib/interface.js:35:43)
      at dbCall (/Users/admin/playground/join-monster/test-api/data/fetch.js:6:24)
      at /Users/admin/playground/join-monster/test-api/schema-paginated/QueryRoot.js:78:69
      at handleUserDbCall (/Users/admin/playground/join-monster/src/util.js:152:18)
      at /Users/admin/playground/join-monster/src/index.js:89:20
      at Generator.next (<anonymous>)
      at step (/Users/admin/playground/join-monster/src/index.js:197:191)
      at /Users/admin/playground/join-monster/src/index.js:197:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
    message: 'SELECT\n  `users`.`id` AS `id`,\n  `users`.`$total` AS `$total`,\n  `users`.`email_address` AS `email`,\n  `users`.`first_name` AS `first_name`,\n  `users`.`last_name` AS `last_name`\nFROM (\n  SELECT `users`.*, count(*) OVER () AS `$total`\n  FROM (SELECT * FROM `accounts`) `users`\n  WHERE TRUE\n  ORDER BY `users`.`id` ASC\n  LIMIT 18446744073709551615 OFFSET 0\n) `users`\nORDER BY `users`.`id` ASC - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'() AS `$total`\n  FROM (SELECT * FROM `accounts`) `users`\n  WHERE TRUE\n  ORDER BY\' at line 7',
    locations: [ [Object] ],
    path: [ 'users' ] } ]
```

**Comment by tslater** [comment]
Looks like mysql doesn't support `COUNT(*) OVER()` https://stackoverflow.com/questions/6292679/mysql-using-correct-syntax-for-the-over-clause

**Comment by tslater** [comment]
I think i figured it out here: `options.dialect = PAGINATE ? 'mariadb' : 'mysql'`. I'm supposed to use Mariadb. I'll try that. If I had the time, I might try and get this documented, or better yet, a script to run all the tests in docker.

**Comment by tslater** [comment]
Ok, acarl005.  Thanks for your help and patience! Here is my latest problem:

```
  21 passed
connection to { client: 'mysql', connection: 'mysql://root:@localhost/test2' }

  9 passed
  1 failed

  should handle pagination in a nested field
  /Users/admin/playground/join-monster/test/pagination/keyset-paging.js:206

   205:   const posts = data.user.posts
   206:   t.deepEqual(posts.pageInfo, {
   207:     hasNextPage: false,        

  Difference:

    {
  -   endCursor: 'eyJjcmVhdGVkX2F0IjoiMjAxNS0xMS0xNVQwODoyNjoxMS4wMDBaIiwiaWQiOjMwfQ==',
  +   endCursor: 'eyJjcmVhdGVkX2F0IjoiMjAxNS0xMS0xNVQwODoyNjoxMS4zMzFaIiwiaWQiOjMwfQ==',
      hasNextPage: false,
      hasPreviousPage: false,
  -   startCursor: 'eyJjcmVhdGVkX2F0IjoiMjAxNi0wNC0xN1QxODo0OToxNS4wMDBaIiwiaWQiOjJ9',
  +   startCursor: 'eyJjcmVhdGVkX2F0IjoiMjAxNi0wNC0xN1QxODo0OToxNS45NDJaIiwiaWQiOjJ9',
    }

  Test.<anonymous> (test/pagination/keyset-paging.js:206:5)
  step (test/pagination/keyset-paging.js:26:191)
```

**Comment by tslater** [comment]
@acarl005, thanks for your patience. I'm on mariadb now and both problems were solved. It did skip some tests, but said "Passed" at the end. Were the skipped tests the oracle ones? Should I be concerned? Also, I am getting some linting errors on lines being too long (this is all before I write any code). Should I be concerned about those either?

**Comment by acarl005** [comment]
The skipped tests are for a known bug that isn't yet fixed, so don't worry about that. The line length is simply a warning, so it will not fail a build. Those are fine. It's just a refactoring chore.

**Comment by tslater** [comment]
Cool. I'm cranking on the meat now. Thanks so much for your help!

**Comment by tslater** [comment]
@acarl005, I've finally got all of the tests passing with the new change. Here's my first go at a PR: https://github.com/stems/join-monster/pull/176

**Comment by tslater** [comment]
@acarl005 It looks like the travis builds are failing: `ERROR 1044 (42000) at line 1: Access denied for user 'travis'@'%' to database 'test1'`, any idea of what I can do to fix that? I had to create the databases locally?

**Comment by acarl005** [comment]
Yeah recently the builds started failing because of that access error. I haven't figured out why yet. Couldn't find any mentions of Travis changing the default username for MariaDB. I'll need to look into it.

**Comment by tslater** [comment]
It's weird, MariaDb doesn't mention a username: https://docs.travis-ci.com/user/database-setup/#MariaDB. MyDQL does: https://docs.travis-ci.com/user/database-setup/#MySQL. I wonder if `root` would work?

**Comment by tslater** [comment]
It looks like root works!! But I'm getting failures that I wasn't getting on localhost. I'm gonna try and sleuth that down now.

**Comment by tslater** [comment]
It looks like root works!! But I'm getting failures that I wasn't getting on localhost. I'm gonna try and sleuth that down now.

**Comment by tslater** [comment]
@acarl005 It looks like all my travis MySQL test are failing (in all versions of NodeJS). They're running just fine locally, is there anyway to get the graphql errors coming out? Or any other tips on how to move forward? https://travis-ci.org/stems/join-monster/jobs/259959323

**Comment by tslater** [comment]
@acarl005 I cheated and outputted the test failure on Travis. https://travis-ci.org/stems/join-monster/jobs/260001701. I get `{ Error: ER_NO_SUCH_TABLE: Table 'test1.accounts' doesn't exist`. It looks like ` npm run db-build` isn't creating those tables? Or is creating the wrong ones? There is no output for that command so it's hard to tell what's up.  Do the tests work on normal branches right now? Is there a (upper/lower) case issue?

I'm not very confident playing around in Travis/with the build stuff. I **hope** that this is helpful and that I'm not being a pain.

**Comment by acarl005** [comment]
Hm. It looks like `npm run db-build` actually failed. You can expand the output by clicking the little arrow on the left-hand side of the commands. It seems to have failed with the same error you had earlier.
```
ERROR 1067 (42000) at line 2: Invalid default value for 'created_at'
```

I think this error is specific to MySQL. It shouldn't even be connecting to MySQL. My intention was to run the tests on Travis against MariaDB instead of MySQL. Maybe the tests are running against MySQL. It's kind of hard to tell which database its actually connected to since the URIs for both begin with `mysql://*`. It looks like both mysql and mariadb are installed in the image. Maybe Travis changed some stuff recently and the builds are installing MySQL even though the test suite doesn't require it. That would explain all the recent build failures... Perhaps theres a way to tell it *not* to install MySQL so we can be certain that its running the tests against MariaDB.

**Comment by acarl005** [comment]
https://stackoverflow.com/questions/45453969/mariadb-clashing-with-mysql-on-travis-ci

**Comment by tslater** [comment]
Great observation. I've confirmed it. On travis I get:
```
0.05s$ mysql -u root -e 'SHOW VARIABLES LIKE "%version%";'
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.6.33                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| version                 | 5.6.33-0ubuntu0.14.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | debian-linux-gnu        |
+-------------------------+-------------------------+
```

On localhost I get:
```
$ mysql -u root -e 'SHOW VARIABLES LIKE "%version%";'
+-------------------------+-----------------------------+
| Variable_name           | Value                       |
+-------------------------+-----------------------------+
| innodb_version          | 5.7.18                      |
| protocol_version        | 10                          |
| slave_type_conversions  |                             |
| version                 | 10.2.7-MariaDB              |
| version_comment         | Homebrew                    |
| version_compile_machine | x86_64                      |
| version_compile_os      | osx10.12                    |
| version_malloc_library  | system                      |
| version_ssl_library     | OpenSSL 1.0.2l  25 May 2017 |
| wsrep_patch_version     | wsrep_25.19                 |
+-------------------------+-----------------------------+
```

**Comment by tslater** [comment]
It looks like the install for MariaDB client failed?
```
The following packages have unmet dependencies:
 libmariadbclient-dev : Depends: libmariadbclient18 (= 5.5.56-1ubuntu0.14.04.1)
E: Unable to correct problems, you have held broken packages.
```

**Comment by tslater** [comment]
It looks like the last successful test passed was in `precise`, but travis upgraded us to `trusty`, as seen under `Build system information`. I've locked `.travis.yml` to `precise` and it passed! Seems like `trusty` is the source of all of our ills. Is that ok, to pass on `precise` for now? It seems like Travis support for MariaDB on `trusty` is no good.

**Comment by tslater** [comment]
Here's the PR link again, with the tests passing: https://github.com/stems/join-monster/pull/176. When you have time, @acarl005, let me know if you want me to change anything. It ended up being a bigger change than I expected. I'm actually super new to GraphQL, Travis, and not a NodeJS developer by trade, so I'm not very confident that what I have will fit perfectly without any adjustments, but it is passing the tests!!!

**Comment by acarl005** [comment]
Thanks for all your help! I'll get this into master before the end of the week.

**Comment by tslater** [comment]
Cool, let me know if you need help with anything.

**Comment by acarl005** [comment]
Included in version **2.0.4**. Thanks for your contribution!

**Comment by tslater** [comment]
Thank you!
